#ifndef _SQLITEKEYWORDS_H_
#define _SQLITEKEYWORDS_H_

#define ANALYZE              "ANALYZE "
#define ATTACH_DATABASE      "ATTACH DATABASE "
#define AUTOINCREMENT        "AUTOINCREMENT "
#define BEGIN_TRANSACTION    "BEGIN TRANSACTION "
#define BETWEEN              "BETWEEN "
#define CHECK                "CHECK "
#define CLI                  "CLI "
#define COMMIT               "COMMIT "
#define CREATE               "CREATE "
#define CREATE_INDEX         "CREATE INDEX "
#define CREATE_TABLE         "CREATE TABLE "
#define CREATE_TRIGGER       "CREATE TRIGGER "
#define CREATE_VIEW          "CREATE VIEW "
#define CREATE_VIRTUAL_TABLE "CREATE VIRTUAL TABLE "
#define DELETE               "DELETE "
#define DETACH_DATABASE      "DETACH DATABASE "
#define DISTINCT             "DISTINCT "
#define DROP_INDEX           "DROP INDEX "
#define DROP_TABLE           "DROP TABLE "
#define DROP_TRIGGER         "DROP TRIGGER "
#define DROP_VIEW            "DROP VIEW "
#define ESCAPE               "ESCAPE "
#define EXISTS                "EXSITS "
#define EXPLAIN              "EXPLAIN "
#define EXPLAIN_QUERY_PLAN   "EXPLAIN QUERY PLAN "
#define FTS_MATCH            "FTS MATCH "
#define GLOB                 "GLOB "
#define GROUP_BY             "GROUP BY "
#define IF                   "IF "
#define IFNEXT               "IF NOT EXISTS "
#define INDEXED_BY           "INDEXED BY "
#define INSERT               "INSERT "
#define INSERT_TABLE         "INSERT INTO "
#define INSTEAD_OF           "INSTEAD OF "
#define INTEGER_PRIMARY_KEY  "INTEGER PRIMARY KEY "
#define LPARENT              "( "
#define RPARENT              ") "
#define LIKE                 "LIKE "
#define MATCH                "MATCH "
#define NOT                  "NOT "
#define NOT_INDEXED          "NOT INDEXED "
#define NOT_NULL             "NOT NULL "
#define ON_CONFLICT          "ON CONFLICT "
#define PRAGMA               "PRAGMA "
#define PRIMARY_KEY          " PRIMARY KEY "
#define PSOW                 "PSOW "
#define REGEXP               "REGEXP "
#define REINDEX              "REINDEX "
#define RELEASE              "RELEASE "
#define REPLACE              "REPLACE "
#define ROLLBACK             "ROLLBACK "
#define ROWID                "ROWID "
#define SAVEPOINT            "SAVEPOINT "
#define SELECT               "SELECT "
#define SLT                  "SLT "
#define UNIQUE               "UNIQUE "
#define UPDATE               "UPDATE "
#define URI                  "URI "
#define VACUUM               "VACUUM "
#define VALUE                " VALUES "
#define VFS                  "VFS "
#define WAL                  "WAL "
#define SEMI                 ";"


#endif /* _SQLITEKEYWORDS_H_ */
