#+TITLE: structure
#+AUTHOR: Yang, Ying-chao
#+OPTIONS: ^:nil author:nil timestamp:nil creator:nil

#+BEGIN_HTML
<span style="color: #0000ff;">Author: </span><a href="http://www.cnblogs.com/yangyingchao" target="_blank">Tubo<span style="color: #0000ff;"><b></b></span></a>
#+END_HTML

#+CAPTION: title

* Base Server (THServer)


  #+BEGIN_SRC text


                          +--------------------+
                          |   SERVER PORT      |   frontend
                          +--------------------+
                          |     PROXY          |
                          +--------------------+
                          |       BROKER       |  backend
                          +---------+----------+
                                    ^
                                    |
          +-------------------------+---------------------------+
          |                         |                           |
          |               +---------+--------+                  |
          |               |                  |                  |
          |               |                  |                  |
          v               v                  v                  v
   +-----------+    +-----------+      +-----------+       +-------------+
   |   Node1   |    |  Node2    |      |  Node3    |       |  NodeN      |
   +-----------+    +-----------+      +-----------+       +-------------+
   |           |    |           |      |           |       |             |
   +-----------+    +-----------+      +-----------+       +-------------+


  #+END_SRC

** Frontend

*** Frontend listens to a port which is used for clients to connect.

*** Port should be specified by command line argument or configuration  file


** Backend

*** Backend is a port that is going to be connected by all server nodes.

*** Should be configured by config file or command line param.

* Server Nodes (WorkerNode)

** Overview

*** Server nodes should be deployed in the same LAN with Base Server.

*** Server Nodes should be added or removed in the run-time.

*** Server Nodes should connect to DB Node(server) when necessary.

** Components

*** Task Leader

    Task Leader manages a number of workers (WorkerThread) and listens messages sent by
    boss (THServer).

**** Number of workers is configured by configure file.

**** Task Leader communicate with boss by NodeMgtAddress specified by configuration.

**** Task Leader communicate with workers though ThreadMgtAddress specified by configuration.

*** Workers

    Workers are responsible for hanlding requests from server.

**** Workers should wait for instructions from leaders before taking over tasks from backend of THServer.

* DataBase Server (DBServer)

** Database server is in separeted Node(Process, or totally on other machine)
